// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodel

var TableNames = struct {
	ActivityLogs    string
	GorpMigrations  string
	GroupLogItems   string
	GroupLogs       string
	Groups          string
	GroupsInvestors string
	Investors       string
}{
	ActivityLogs:    "activity_logs",
	GorpMigrations:  "gorp_migrations",
	GroupLogItems:   "group_log_items",
	GroupLogs:       "group_logs",
	Groups:          "groups",
	GroupsInvestors: "groups_investors",
	Investors:       "investors",
}
