// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodel

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// GroupsInvestor is an object representing the database table.
type GroupsInvestor struct {
	ID         int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	InvestorID int64     `boil:"investor_id" json:"investor_id" toml:"investor_id" yaml:"investor_id"`
	GroupID    int64     `boil:"group_id" json:"group_id" toml:"group_id" yaml:"group_id"`
	CreatedAt  time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt  time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	DeletedAt  null.Time `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`

	R *groupsInvestorR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L groupsInvestorL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var GroupsInvestorColumns = struct {
	ID         string
	InvestorID string
	GroupID    string
	CreatedAt  string
	UpdatedAt  string
	DeletedAt  string
}{
	ID:         "id",
	InvestorID: "investor_id",
	GroupID:    "group_id",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
	DeletedAt:  "deleted_at",
}

// Generated where

var GroupsInvestorWhere = struct {
	ID         whereHelperint64
	InvestorID whereHelperint64
	GroupID    whereHelperint64
	CreatedAt  whereHelpertime_Time
	UpdatedAt  whereHelpertime_Time
	DeletedAt  whereHelpernull_Time
}{
	ID:         whereHelperint64{field: "\"groups_investors\".\"id\""},
	InvestorID: whereHelperint64{field: "\"groups_investors\".\"investor_id\""},
	GroupID:    whereHelperint64{field: "\"groups_investors\".\"group_id\""},
	CreatedAt:  whereHelpertime_Time{field: "\"groups_investors\".\"created_at\""},
	UpdatedAt:  whereHelpertime_Time{field: "\"groups_investors\".\"updated_at\""},
	DeletedAt:  whereHelpernull_Time{field: "\"groups_investors\".\"deleted_at\""},
}

// GroupsInvestorRels is where relationship names are stored.
var GroupsInvestorRels = struct {
	Group    string
	Investor string
}{
	Group:    "Group",
	Investor: "Investor",
}

// groupsInvestorR is where relationships are stored.
type groupsInvestorR struct {
	Group    *Group
	Investor *Investor
}

// NewStruct creates a new relationship struct
func (*groupsInvestorR) NewStruct() *groupsInvestorR {
	return &groupsInvestorR{}
}

// groupsInvestorL is where Load methods for each relationship are stored.
type groupsInvestorL struct{}

var (
	groupsInvestorAllColumns            = []string{"id", "investor_id", "group_id", "created_at", "updated_at", "deleted_at"}
	groupsInvestorColumnsWithoutDefault = []string{"investor_id", "group_id", "deleted_at"}
	groupsInvestorColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	groupsInvestorPrimaryKeyColumns     = []string{"id"}
)

type (
	// GroupsInvestorSlice is an alias for a slice of pointers to GroupsInvestor.
	// This should generally be used opposed to []GroupsInvestor.
	GroupsInvestorSlice []*GroupsInvestor
	// GroupsInvestorHook is the signature for custom GroupsInvestor hook methods
	GroupsInvestorHook func(context.Context, boil.ContextExecutor, *GroupsInvestor) error

	groupsInvestorQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	groupsInvestorType                 = reflect.TypeOf(&GroupsInvestor{})
	groupsInvestorMapping              = queries.MakeStructMapping(groupsInvestorType)
	groupsInvestorPrimaryKeyMapping, _ = queries.BindMapping(groupsInvestorType, groupsInvestorMapping, groupsInvestorPrimaryKeyColumns)
	groupsInvestorInsertCacheMut       sync.RWMutex
	groupsInvestorInsertCache          = make(map[string]insertCache)
	groupsInvestorUpdateCacheMut       sync.RWMutex
	groupsInvestorUpdateCache          = make(map[string]updateCache)
	groupsInvestorUpsertCacheMut       sync.RWMutex
	groupsInvestorUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var groupsInvestorBeforeInsertHooks []GroupsInvestorHook
var groupsInvestorBeforeUpdateHooks []GroupsInvestorHook
var groupsInvestorBeforeDeleteHooks []GroupsInvestorHook
var groupsInvestorBeforeUpsertHooks []GroupsInvestorHook

var groupsInvestorAfterInsertHooks []GroupsInvestorHook
var groupsInvestorAfterSelectHooks []GroupsInvestorHook
var groupsInvestorAfterUpdateHooks []GroupsInvestorHook
var groupsInvestorAfterDeleteHooks []GroupsInvestorHook
var groupsInvestorAfterUpsertHooks []GroupsInvestorHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *GroupsInvestor) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range groupsInvestorBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *GroupsInvestor) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range groupsInvestorBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *GroupsInvestor) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range groupsInvestorBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *GroupsInvestor) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range groupsInvestorBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *GroupsInvestor) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range groupsInvestorAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *GroupsInvestor) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range groupsInvestorAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *GroupsInvestor) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range groupsInvestorAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *GroupsInvestor) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range groupsInvestorAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *GroupsInvestor) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range groupsInvestorAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddGroupsInvestorHook registers your hook function for all future operations.
func AddGroupsInvestorHook(hookPoint boil.HookPoint, groupsInvestorHook GroupsInvestorHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		groupsInvestorBeforeInsertHooks = append(groupsInvestorBeforeInsertHooks, groupsInvestorHook)
	case boil.BeforeUpdateHook:
		groupsInvestorBeforeUpdateHooks = append(groupsInvestorBeforeUpdateHooks, groupsInvestorHook)
	case boil.BeforeDeleteHook:
		groupsInvestorBeforeDeleteHooks = append(groupsInvestorBeforeDeleteHooks, groupsInvestorHook)
	case boil.BeforeUpsertHook:
		groupsInvestorBeforeUpsertHooks = append(groupsInvestorBeforeUpsertHooks, groupsInvestorHook)
	case boil.AfterInsertHook:
		groupsInvestorAfterInsertHooks = append(groupsInvestorAfterInsertHooks, groupsInvestorHook)
	case boil.AfterSelectHook:
		groupsInvestorAfterSelectHooks = append(groupsInvestorAfterSelectHooks, groupsInvestorHook)
	case boil.AfterUpdateHook:
		groupsInvestorAfterUpdateHooks = append(groupsInvestorAfterUpdateHooks, groupsInvestorHook)
	case boil.AfterDeleteHook:
		groupsInvestorAfterDeleteHooks = append(groupsInvestorAfterDeleteHooks, groupsInvestorHook)
	case boil.AfterUpsertHook:
		groupsInvestorAfterUpsertHooks = append(groupsInvestorAfterUpsertHooks, groupsInvestorHook)
	}
}

// One returns a single groupsInvestor record from the query.
func (q groupsInvestorQuery) One(ctx context.Context, exec boil.ContextExecutor) (*GroupsInvestor, error) {
	o := &GroupsInvestor{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodel: failed to execute a one query for groups_investors")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all GroupsInvestor records from the query.
func (q groupsInvestorQuery) All(ctx context.Context, exec boil.ContextExecutor) (GroupsInvestorSlice, error) {
	var o []*GroupsInvestor

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbmodel: failed to assign all query results to GroupsInvestor slice")
	}

	if len(groupsInvestorAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all GroupsInvestor records in the query.
func (q groupsInvestorQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: failed to count groups_investors rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q groupsInvestorQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbmodel: failed to check if groups_investors exists")
	}

	return count > 0, nil
}

// Group pointed to by the foreign key.
func (o *GroupsInvestor) Group(mods ...qm.QueryMod) groupQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.GroupID),
	}

	queryMods = append(queryMods, mods...)

	query := Groups(queryMods...)
	queries.SetFrom(query.Query, "\"groups\"")

	return query
}

// Investor pointed to by the foreign key.
func (o *GroupsInvestor) Investor(mods ...qm.QueryMod) investorQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.InvestorID),
	}

	queryMods = append(queryMods, mods...)

	query := Investors(queryMods...)
	queries.SetFrom(query.Query, "\"investors\"")

	return query
}

// LoadGroup allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (groupsInvestorL) LoadGroup(ctx context.Context, e boil.ContextExecutor, singular bool, maybeGroupsInvestor interface{}, mods queries.Applicator) error {
	var slice []*GroupsInvestor
	var object *GroupsInvestor

	if singular {
		object = maybeGroupsInvestor.(*GroupsInvestor)
	} else {
		slice = *maybeGroupsInvestor.(*[]*GroupsInvestor)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &groupsInvestorR{}
		}
		args = append(args, object.GroupID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &groupsInvestorR{}
			}

			for _, a := range args {
				if a == obj.GroupID {
					continue Outer
				}
			}

			args = append(args, obj.GroupID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`groups`), qm.WhereIn(`groups.id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Group")
	}

	var resultSlice []*Group
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Group")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for groups")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for groups")
	}

	if len(groupsInvestorAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Group = foreign
		if foreign.R == nil {
			foreign.R = &groupR{}
		}
		foreign.R.GroupsInvestors = append(foreign.R.GroupsInvestors, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.GroupID == foreign.ID {
				local.R.Group = foreign
				if foreign.R == nil {
					foreign.R = &groupR{}
				}
				foreign.R.GroupsInvestors = append(foreign.R.GroupsInvestors, local)
				break
			}
		}
	}

	return nil
}

// LoadInvestor allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (groupsInvestorL) LoadInvestor(ctx context.Context, e boil.ContextExecutor, singular bool, maybeGroupsInvestor interface{}, mods queries.Applicator) error {
	var slice []*GroupsInvestor
	var object *GroupsInvestor

	if singular {
		object = maybeGroupsInvestor.(*GroupsInvestor)
	} else {
		slice = *maybeGroupsInvestor.(*[]*GroupsInvestor)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &groupsInvestorR{}
		}
		args = append(args, object.InvestorID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &groupsInvestorR{}
			}

			for _, a := range args {
				if a == obj.InvestorID {
					continue Outer
				}
			}

			args = append(args, obj.InvestorID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`investors`), qm.WhereIn(`investors.id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Investor")
	}

	var resultSlice []*Investor
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Investor")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for investors")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for investors")
	}

	if len(groupsInvestorAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Investor = foreign
		if foreign.R == nil {
			foreign.R = &investorR{}
		}
		foreign.R.GroupsInvestors = append(foreign.R.GroupsInvestors, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.InvestorID == foreign.ID {
				local.R.Investor = foreign
				if foreign.R == nil {
					foreign.R = &investorR{}
				}
				foreign.R.GroupsInvestors = append(foreign.R.GroupsInvestors, local)
				break
			}
		}
	}

	return nil
}

// SetGroup of the groupsInvestor to the related item.
// Sets o.R.Group to related.
// Adds o to related.R.GroupsInvestors.
func (o *GroupsInvestor) SetGroup(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Group) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"groups_investors\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"group_id"}),
		strmangle.WhereClause("\"", "\"", 0, groupsInvestorPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.GroupID = related.ID
	if o.R == nil {
		o.R = &groupsInvestorR{
			Group: related,
		}
	} else {
		o.R.Group = related
	}

	if related.R == nil {
		related.R = &groupR{
			GroupsInvestors: GroupsInvestorSlice{o},
		}
	} else {
		related.R.GroupsInvestors = append(related.R.GroupsInvestors, o)
	}

	return nil
}

// SetInvestor of the groupsInvestor to the related item.
// Sets o.R.Investor to related.
// Adds o to related.R.GroupsInvestors.
func (o *GroupsInvestor) SetInvestor(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Investor) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"groups_investors\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"investor_id"}),
		strmangle.WhereClause("\"", "\"", 0, groupsInvestorPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.InvestorID = related.ID
	if o.R == nil {
		o.R = &groupsInvestorR{
			Investor: related,
		}
	} else {
		o.R.Investor = related
	}

	if related.R == nil {
		related.R = &investorR{
			GroupsInvestors: GroupsInvestorSlice{o},
		}
	} else {
		related.R.GroupsInvestors = append(related.R.GroupsInvestors, o)
	}

	return nil
}

// GroupsInvestors retrieves all the records using an executor.
func GroupsInvestors(mods ...qm.QueryMod) groupsInvestorQuery {
	mods = append(mods, qm.From("\"groups_investors\""))
	return groupsInvestorQuery{NewQuery(mods...)}
}

// FindGroupsInvestor retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindGroupsInvestor(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*GroupsInvestor, error) {
	groupsInvestorObj := &GroupsInvestor{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"groups_investors\" where \"id\"=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, groupsInvestorObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodel: unable to select from groups_investors")
	}

	return groupsInvestorObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *GroupsInvestor) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbmodel: no groups_investors provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(groupsInvestorColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	groupsInvestorInsertCacheMut.RLock()
	cache, cached := groupsInvestorInsertCache[key]
	groupsInvestorInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			groupsInvestorAllColumns,
			groupsInvestorColumnsWithDefault,
			groupsInvestorColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(groupsInvestorType, groupsInvestorMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(groupsInvestorType, groupsInvestorMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"groups_investors\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"groups_investors\" () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT \"%s\" FROM \"groups_investors\" WHERE %s", strings.Join(returnColumns, "\",\""), strmangle.WhereClause("\"", "\"", 0, groupsInvestorPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "dbmodel: unable to insert into groups_investors")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == groupsInvestorMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "dbmodel: unable to populate default values for groups_investors")
	}

CacheNoHooks:
	if !cached {
		groupsInvestorInsertCacheMut.Lock()
		groupsInvestorInsertCache[key] = cache
		groupsInvestorInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the GroupsInvestor.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *GroupsInvestor) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	groupsInvestorUpdateCacheMut.RLock()
	cache, cached := groupsInvestorUpdateCache[key]
	groupsInvestorUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			groupsInvestorAllColumns,
			groupsInvestorPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbmodel: unable to update groups_investors, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"groups_investors\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, groupsInvestorPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(groupsInvestorType, groupsInvestorMapping, append(wl, groupsInvestorPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to update groups_investors row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: failed to get rows affected by update for groups_investors")
	}

	if !cached {
		groupsInvestorUpdateCacheMut.Lock()
		groupsInvestorUpdateCache[key] = cache
		groupsInvestorUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q groupsInvestorQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to update all for groups_investors")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to retrieve rows affected for groups_investors")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o GroupsInvestorSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbmodel: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), groupsInvestorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"groups_investors\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, groupsInvestorPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to update all in groupsInvestor slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to retrieve rows affected all in update all groupsInvestor")
	}
	return rowsAff, nil
}

// Delete deletes a single GroupsInvestor record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *GroupsInvestor) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbmodel: no GroupsInvestor provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), groupsInvestorPrimaryKeyMapping)
	sql := "DELETE FROM \"groups_investors\" WHERE \"id\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to delete from groups_investors")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: failed to get rows affected by delete for groups_investors")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q groupsInvestorQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbmodel: no groupsInvestorQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to delete all from groups_investors")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: failed to get rows affected by deleteall for groups_investors")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o GroupsInvestorSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(groupsInvestorBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), groupsInvestorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"groups_investors\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, groupsInvestorPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to delete all from groupsInvestor slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: failed to get rows affected by deleteall for groups_investors")
	}

	if len(groupsInvestorAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *GroupsInvestor) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindGroupsInvestor(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *GroupsInvestorSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := GroupsInvestorSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), groupsInvestorPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"groups_investors\".* FROM \"groups_investors\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, groupsInvestorPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbmodel: unable to reload all in GroupsInvestorSlice")
	}

	*o = slice

	return nil
}

// GroupsInvestorExists checks if the GroupsInvestor row exists.
func GroupsInvestorExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"groups_investors\" where \"id\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbmodel: unable to check if groups_investors exists")
	}

	return exists, nil
}
